import { Patient } from "@/features/patients/types/patient";

export const Patients: Patient[] = [
  {
    id: "1",
    mrn: "MRN000001",
    firstName: "John",
    middleName: "Michael",
    lastName: "Doe",
    preferredName: "Johnny",
    gender: "Male",
    dateOfBirth: "1992-03-15",
    maritalStatus: "Single",
    age: 33,
    phoneNumber: "+233241111111",
    alternatePhoneNumber: "+233201111111",
    email: "john.doe@example.com",
    nationality: "Ghanaian",
    nationalId: "GHA-123456789",
    address: "12 Oxford Street",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    bloodGroup: "O+",
    genotype: "AA",
    status: "ACTIVE",
    registeredAt: "2024-01-10T10:00:00Z",
    emergencyContactName: "Jane Doe",
    emergencyContactPhone: "+233245555555",
    emergencyContactRelationship: "Sister",
    patientType: "OUTPATIENT",
  },
  {
    id: "2",
    mrn: "MRN000002",
    firstName: "Jane",
    lastName: "Smith",
    preferredName: "Jane",
    gender: "Female",
    dateOfBirth: "1995-07-20",
    age: 30,
    phoneNumber: "+233242222222",
    email: "jane.smith@example.com",
    nationality: "Ghanaian",
    nationalId: "GHA-987654321",
    address: "5 Ring Road",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    bloodGroup: "A+",
    genotype: "AS",
    status: "ACTIVE",
    registeredAt: "2024-02-14T08:30:00Z",
    patientType: "OUTPATIENT",
  },
  {
    id: "3",
    mrn: "MRN000003",
    firstName: "Bob",
    lastName: "Wilson",
    preferredName: "Bob",
    gender: "Male",
    dateOfBirth: "1980-11-08",
    age: 45,
    phoneNumber: "+233243333333",
    email: "bob.wilson@example.com",
    address: "Tamale",
    city: "Tamale",
    region: "Northern",
    country: "Ghana",
    bloodGroup: "B+",
    genotype: "AA",
    status: "INACTIVE",
    registeredAt: "2023-11-12T14:20:00Z",
    patientType: "INPATIENT",
  },
  {
    id: "4",
    mrn: "MRN000004",
    firstName: "Alice",
    lastName: "Brown",
    preferredName: "Alice",
    gender: "Female",
    dateOfBirth: "1989-05-25",
    age: 36,
    phoneNumber: "+233244444444",
    email: "alice.brown@example.com",
    address: "Cape Coast",
    city: "Cape Coast",
    region: "Central",
    country: "Ghana",
    bloodGroup: "AB+",
    genotype: "AA",
    status: "ACTIVE",
    registeredAt: "2024-03-01T09:45:00Z",
    patientType: "OUTPATIENT",
  },
  {
    id: "5",
    mrn: "MRN000005",
    firstName: "Charlie",
    lastName: "Davis",
    preferredName: "Charlie",
    gender: "Male",
    dateOfBirth: "1998-09-18",
    age: 27,
    phoneNumber: "+233245555555",
    email: "charlie.davis@example.com",
    address: "Kumasi",
    city: "Kumasi",
    region: "Ashanti",
    country: "Ghana",
    bloodGroup: "O-",
    genotype: "AS",
    status: "ACTIVE",
    registeredAt: "2024-04-18T11:15:00Z",
    patientType: "OUTPATIENT",
  },
  {
    id: "6",
    mrn: "MRN000006",
    firstName: "Emily",
    lastName: "Johnson",
    preferredName: "Emily",
    gender: "Female",
    dateOfBirth: "1993-12-10",
    age: 31,
    phoneNumber: "+233246666666",
    email: "emily.johnson@example.com",
    address: "Tema",
    city: "Tema",
    region: "Greater Accra",
    country: "Ghana",
    bloodGroup: "A-",
    genotype: "AA",
    status: "ACTIVE",
    registeredAt: "2024-05-20T13:10:00Z",
    patientType: "INPATIENT",
  },
];


// user-data.ts

export const PatientSummaryMock = {
  totalVisits: 15,
  activeMedications: 4,
  allegies: 2,
  activeProblems: 3,
  outstandingBalance: 120.00,
  lastVisitDate: "2025-12-20",
};