/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/facilities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put: operations["update"];
        post?: never;
        delete: operations["deactivate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["onboard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FacilityAddressRequest: {
            line1: string;
            line2?: string;
            city: string;
            stateOrRegion: string;
            country: string;
            postalCode?: string;
        };
        UpdateFacilityRequest: {
            name: string;
            type: string;
            location: components["schemas"]["FacilityAddressRequest"];
            contactPhone: string;
            contactEmail?: string;
        };
        FacilityAddressResponse: {
            line1?: string;
            line2?: string;
            city?: string;
            state?: string;
            postalCode?: string;
            country?: string;
        };
        FacilityResponse: {
            facilityId?: string;
            code?: string;
            name?: string;
            type?: string;
            location?: components["schemas"]["FacilityAddressResponse"];
            contactPhone?: string;
            contactEmail?: string;
            status?: string;
            createdAt?: string;
            updateAt?: string;
        };
        AddressRequest: {
            line1: string;
            line2?: string;
            city: string;
            state?: string;
            postalCode?: string;
            country: string;
        };
        ContactDetailsRequest: {
            homeAddress: components["schemas"]["AddressRequest"];
            phoneNumber: string;
            alternatePhone?: string;
            email?: string;
        };
        InsuranceInformationRequest: {
            provider?: string;
            policyNumber?: string;
            groupNumber?: string;
            /** Format: date */
            coverageStartDate?: string;
            /** Format: date */
            expirationDate?: string;
        };
        MedicalDetailsRequest: {
            bloodGroup: string;
            genoType: string;
            nationalIdType?: string;
            nationalIdNumber?: string;
            nationalIdIssuingCountry?: string;
        };
        NextOfKinRequest: {
            fullName: string;
            relationship: string;
            phoneNumber: string;
            address?: components["schemas"]["AddressRequest"];
        };
        PersonalDetailsRequest: {
            firstName: string;
            lastName: string;
            maidenName?: string;
            preferredName?: string;
            gender: string;
            maritalStatus: string;
            /** Format: date */
            dateOfBirth: string;
            religion: string;
            nationality: string;
            ethnicity: string;
            occupation: string;
        };
        RegisterPatientRequest: {
            personalDetails: components["schemas"]["PersonalDetailsRequest"];
            medicalDetails: components["schemas"]["MedicalDetailsRequest"];
            contactDetails: components["schemas"]["ContactDetailsRequest"];
            nextOfKin: components["schemas"]["NextOfKinRequest"];
            insuranceInformation?: components["schemas"]["InsuranceInformationRequest"];
            patientType: string;
            preferredLanguage: string;
            /** Format: uuid */
            facilityId: string;
        };
        RegisterPatientResponse: {
            patientId?: string;
        };
        OnboardFacilityRequest: {
            code: string;
            name: string;
            type: string;
            location: components["schemas"]["FacilityAddressRequest"];
            contactPhone: string;
            contactEmail?: string;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        LoginResponse: {
            accessToken?: string;
            accessTokenExpiresAt?: string;
            refreshToken?: string;
            refreshTokenExpiresAt?: string;
            staffId?: string;
            fullName?: string;
            role?: string;
            mustChangePassword?: boolean;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        CreateCredentialRequest: {
            /** Format: uuid */
            staffId: string;
            loginEmail: string;
            temporaryPassword: string;
        };
        ApiResponsePagedResponseFacilityResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PagedResponseFacilityResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        PagedResponseFacilityResponse: {
            content?: components["schemas"]["FacilityResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        ApiResponseFacilitySummaryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["FacilitySummaryResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        FacilitySummaryResponse: {
            /** Format: int64 */
            totalFacilities?: number;
            /** Format: int64 */
            activeFacilities?: number;
            /** Format: int64 */
            inactiveFacilities?: number;
            /** Format: int64 */
            pendingFacilities?: number;
            countType?: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFacilityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityResponse"];
                };
            };
        };
    };
    deactivate: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPatientRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterPatientResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "INACTIVE" | "PENDING_APPROVAL";
                type?: "TEACHING_HOSPITAL" | "REGIONAL_HOSPITAL" | "DISTRICT_HOSPITAL" | "CLINIC" | "POLYCLINIC";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePagedResponseFacilityResponse"];
                };
            };
        };
    };
    onboard: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardFacilityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityResponse"];
                };
            };
        };
    };
    reactivate: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCredentialRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseFacilitySummaryResponse"];
                };
            };
        };
    };
}
